configs:
  - id: baseline-availability-slo
    type:
      settings:
        schema: builtin:slo
        scope: environment
    config:
      name: baseline-availability-slo
      template: slo.json
      parameters:
        sloName:
          type: value
          value: dt-pilot-baseline-availability
        targetPct:
          type: value
          value: 99.5
        warningPct:
          type: value
          value: 99.8
        managementZoneId: [ builtin:management-zones, baseline-services, id ]
